Repository collection, text details, Concept list and details
diging/vogon-web-client pull request #11
Opened 2019-11-18 21:57 UTC by nowke

2019-12-02 21:07 UTC, tjquinn1 requested changes

2019-12-02 21:07 UTC, tjquinn1 commented on src/App.vue
> +.main {
Do you actually use this class?

2019-12-02 21:07 UTC, tjquinn1 commented on src/views/concepts/ConceptList.vue
> +<template lang="pug">
This page renders but will not load anything.  I have attached screen shots of the errors

![Screen Shot 2019-12-02 at 1 55 13 PM](https://user-images.githubusercontent.com/16781171/69994696-a711b300-150b-11ea-99ed-7d7cba941b29.png)
![Screen Shot 2019-12-02 at 1 55 20 PM](https://user-images.githubusercontent.com/16781171/69994705-ab3dd080-150b-11ea-9f00-82d05e286edd.png)

2019-12-04 16:14 UTC, nowke commented on src/App.vue
> +.main {
Yes. It is used in all pages as containers.

2019-12-04 16:17 UTC, nowke commented on src/views/concepts/ConceptList.vue
> +<template lang="pug">
Related to backend https://github.com/diging/vogon-web/pull/155

2020-01-07 17:34 UTC, tjquinn1 approved these changes

2020-01-07 17:34 UTC, merged