[VGNWB-311] Added pagination for collections
diging/vogon-web-client pull request #27
Opened 2020-02-28 22:35 UTC by Rudi114

2020-02-28 23:01 UTC, tjquinn1 requested changes
It looks good, lets just make the rows per page text a little bigger.

2020-02-28 23:21 UTC, Rudi114 commented
Font Size increased

2020-03-02 20:11 UTC, tjquinn1 requested changes

2020-03-02 20:11 UTC, tjquinn1 commented on src/components/texts/RepoCollections.vue
> +.rows {
This needs to be named something else. You should be careful with class names. When you use grids in vuetify it just creates a div with the class row. Had you used rows in this you would have changed all the rows. This is usually the case with most css framworks as well e.g. bootstrap. I have added a screenshot so you can see what the rendered rows look like, it maybe helpful to look through the code that is rendered in the browers and read some documentation.

<img width="367" alt="Screen Shot 2020-03-02 at 1 06 41 PM" src="https://user-images.githubusercontent.com/16781171/75713459-102dd180-5c87-11ea-8900-c041d0738980.png">

2020-03-02 20:11 UTC, tjquinn1 commented on src/components/texts/RepoCollections.vue
> +.rows {
Also lets take the front size down just a little as well

2020-03-05 22:54 UTC, tjquinn1 approved these changes

2020-03-05 22:54 UTC, merged