[VGNWB-330] Disable annotate button if text is pending
diging/vogon-web-client pull request #34
Opened 2020-03-18 23:10 UTC by nowke

2020-07-21 20:53 UTC, tjquinn1 commented
see backend.

2020-08-11 19:04 UTC, nowke commented
Fixed Backend PR

2020-08-12 20:39 UTC, tjquinn1 requested changes

2020-08-12 20:39 UTC, tjquinn1 commented on src/views/texts/TextDetails.vue
> +					) The item is still pending with Giles. Wait until then for starting annotations
Lets change GIles is pending to amphora is pending. Users probably wont know what Giles is but they will know what amphora is.

2020-09-02 17:48 UTC, merged